- name: configure backend server
  become: yes
  hosts: backend
  vars: 
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y


  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf: dnf install nodejs -y
      name: nodejs
      state: installed


  - name: create expense user
    ansible.builtin.user:
      name: expense