- name: configure backend server
  become: yes
  hosts: backend
  vars:
    login_host: db.daws78s.online
    login_password: ExpenseApp@1
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf: # only works for Redhat family
      name: "{{ item }}"
      state: installed