- name: configure db server
  hosts: db.samfuturetech.cloud
  become: yes
  vars:
    login_host: db.samfuturetech.cloud
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter mysql root password
    private: no
  tasks:
  - name: install MYSQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install python mysql dependencies
    ansible.builtin.pip:
      name:
      - pyMYSQL
      - cryptography
      executable: pip3.9



- name: Check MySQL Connection
  hosts: db_servers
  gather_facts: no
  tasks:
    - name: Get MySQL Server Info
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
      register: mysql_info_result

    - name: Print MySQL Info
      debug:
        var: mysql_info_result

- name: setup root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}}"
  when: mysql_connection_output.failed is true





      
